#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^3'
bspc rule -a discord desktop='^1'
bspc rule -a Slack desktop='^1'
bspc rule -a Termite desktop='^2'

bspc config normal_border_color "#A14E61"
bspc config focused_border_color "#d59fd5"

compton --config ~/.config/compton/test.conf &
bash ~/.config/polybar/launch.sh &
bash ~/.config/bspwm/alscript.sh &
wal -i /home/ser3n1ty/Pictures/Wallpapers/XXI3y4g.jpg
